version: '3'
services:
    config-server:
        build: spring-cloud-config-server
        ports:
          - 8888:8888
    client:
        build: spring-boot-client
        ports:
          - 8889:8889
        depends_on:
          - config-server
    