//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.28 at 03:25:08 PM IST 
//


package com.cft.pts.payment.processing.integration.iso20022.model.wire.pain00100108;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalInformationWire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalInformationWire"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClntAddtn" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}CDATA" minOccurs="0"/&gt;
 *         &lt;element name="BizInf" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}BusinessInformation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalInformationWire", namespace = "urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06", propOrder = {
    "clntAddtn",
    "bizInf"
})
public class AdditionalInformationWire
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ClntAddtn", namespace = "urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06")
    protected String clntAddtn;
    @XmlElement(name = "BizInf", namespace = "urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06", required = true)
    protected BusinessInformation bizInf;

    /**
     * Gets the value of the clntAddtn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntAddtn() {
        return clntAddtn;
    }

    /**
     * Sets the value of the clntAddtn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntAddtn(String value) {
        this.clntAddtn = value;
    }

    /**
     * Gets the value of the bizInf property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessInformation }
     *     
     */
    public BusinessInformation getBizInf() {
        return bizInf;
    }

    /**
     * Sets the value of the bizInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessInformation }
     *     
     */
    public void setBizInf(BusinessInformation value) {
        this.bizInf = value;
    }

}
