//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.28 at 03:25:08 PM IST 
//


package com.cft.pts.payment.processing.integration.iso20022.model.wire.pain00100108;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalLocalInstrument1CodeWire.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExternalLocalInstrument1CodeWire"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BTR"/&gt;
 *     &lt;enumeration value="CTP"/&gt;
 *     &lt;enumeration value="CTR"/&gt;
 *     &lt;enumeration value="DRC"/&gt;
 *     &lt;enumeration value="DRB"/&gt;
 *     &lt;enumeration value="DRW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ExternalLocalInstrument1CodeWire", namespace = "urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06")
@XmlEnum
public enum ExternalLocalInstrument1CodeWire {

    BTR,
    CTP,
    CTR,
    DRC,
    DRB,
    DRW;

    public String value() {
        return name();
    }

    public static ExternalLocalInstrument1CodeWire fromValue(String v) {
        return valueOf(v);
    }

}
