//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.28 at 03:25:08 PM IST 
//


package com.cft.pts.payment.processing.integration.iso20022.model.wire.pain00100108;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalOrganisationIdentification1CodeWire.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExternalOrganisationIdentification1CodeWire"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BANK"/&gt;
 *     &lt;enumeration value="CUST"/&gt;
 *     &lt;enumeration value="DUNS"/&gt;
 *     &lt;enumeration value="EMPL"/&gt;
 *     &lt;enumeration value="GS1G"/&gt;
 *     &lt;enumeration value="TXID"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ExternalOrganisationIdentification1CodeWire", namespace = "urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06")
@XmlEnum
public enum ExternalOrganisationIdentification1CodeWire {

    BANK("BANK"),
    CUST("CUST"),
    DUNS("DUNS"),
    EMPL("EMPL"),
    @XmlEnumValue("GS1G")
    GS_1_G("GS1G"),
    TXID("TXID");
    private final String value;

    ExternalOrganisationIdentification1CodeWire(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExternalOrganisationIdentification1CodeWire fromValue(String v) {
        for (ExternalOrganisationIdentification1CodeWire c: ExternalOrganisationIdentification1CodeWire.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
