//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 02:29:15 PM IST 
//


package com.sample.pain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalInformationWire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalInformationWire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClntAddtn" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}CDATA" minOccurs="0"/>
 *         &lt;element name="BizInf" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}BusinessInformation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalInformationWire", propOrder = {
    "clntAddtn",
    "bizInf"
})
public class AdditionalInformationWire {

    @XmlElement(name = "ClntAddtn")
    protected String clntAddtn;
    @XmlElement(name = "BizInf", required = true)
    protected BusinessInformation bizInf;

    /**
     * Gets the value of the clntAddtn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClntAddtn() {
        return clntAddtn;
    }

    /**
     * Sets the value of the clntAddtn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClntAddtn(String value) {
        this.clntAddtn = value;
    }

    /**
     * Gets the value of the bizInf property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessInformation }
     *     
     */
    public BusinessInformation getBizInf() {
        return bizInf;
    }

    /**
     * Sets the value of the bizInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessInformation }
     *     
     */
    public void setBizInf(BusinessInformation value) {
        this.bizInf = value;
    }

}
