//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 02:29:15 PM IST 
//


package com.sample.pain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChanlCd" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}Max7Text"/>
 *         &lt;element name="AcctClsr" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}TrueFalseIndicator" minOccurs="0"/>
 *         &lt;element name="RgltryOvrrd" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}TrueFalseIndicator" minOccurs="0"/>
 *         &lt;element name="ChrgsWvd" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}TrueFalseIndicator" minOccurs="0"/>
 *         &lt;element name="ChrgsApldAmt" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}ActiveOrHistoricCurrencyAndAmount" minOccurs="0"/>
 *         &lt;element name="TxTpCd" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}Max3Text" minOccurs="0"/>
 *         &lt;element name="RcvrFIInf" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}Max195Text" minOccurs="0"/>
 *         &lt;element name="XchgRateDealId" type="{urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06}Max35Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessInformation", propOrder = {
    "chanlCd",
    "acctClsr",
    "rgltryOvrrd",
    "chrgsWvd",
    "chrgsApldAmt",
    "txTpCd",
    "rcvrFIInf",
    "xchgRateDealId"
})
public class BusinessInformation {

    @XmlElement(name = "ChanlCd", required = true)
    protected String chanlCd;
    @XmlElement(name = "AcctClsr")
    protected Boolean acctClsr;
    @XmlElement(name = "RgltryOvrrd")
    protected Boolean rgltryOvrrd;
    @XmlElement(name = "ChrgsWvd")
    protected Boolean chrgsWvd;
    @XmlElement(name = "ChrgsApldAmt")
    protected ActiveOrHistoricCurrencyAndAmount chrgsApldAmt;
    @XmlElement(name = "TxTpCd")
    protected String txTpCd;
    @XmlElement(name = "RcvrFIInf")
    protected String rcvrFIInf;
    @XmlElement(name = "XchgRateDealId")
    protected String xchgRateDealId;

    /**
     * Gets the value of the chanlCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChanlCd() {
        return chanlCd;
    }

    /**
     * Sets the value of the chanlCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChanlCd(String value) {
        this.chanlCd = value;
    }

    /**
     * Gets the value of the acctClsr property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcctClsr() {
        return acctClsr;
    }

    /**
     * Sets the value of the acctClsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcctClsr(Boolean value) {
        this.acctClsr = value;
    }

    /**
     * Gets the value of the rgltryOvrrd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRgltryOvrrd() {
        return rgltryOvrrd;
    }

    /**
     * Sets the value of the rgltryOvrrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRgltryOvrrd(Boolean value) {
        this.rgltryOvrrd = value;
    }

    /**
     * Gets the value of the chrgsWvd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChrgsWvd() {
        return chrgsWvd;
    }

    /**
     * Sets the value of the chrgsWvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChrgsWvd(Boolean value) {
        this.chrgsWvd = value;
    }

    /**
     * Gets the value of the chrgsApldAmt property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveOrHistoricCurrencyAndAmount }
     *     
     */
    public ActiveOrHistoricCurrencyAndAmount getChrgsApldAmt() {
        return chrgsApldAmt;
    }

    /**
     * Sets the value of the chrgsApldAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveOrHistoricCurrencyAndAmount }
     *     
     */
    public void setChrgsApldAmt(ActiveOrHistoricCurrencyAndAmount value) {
        this.chrgsApldAmt = value;
    }

    /**
     * Gets the value of the txTpCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxTpCd() {
        return txTpCd;
    }

    /**
     * Sets the value of the txTpCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxTpCd(String value) {
        this.txTpCd = value;
    }

    /**
     * Gets the value of the rcvrFIInf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvrFIInf() {
        return rcvrFIInf;
    }

    /**
     * Sets the value of the rcvrFIInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvrFIInf(String value) {
        this.rcvrFIInf = value;
    }

    /**
     * Gets the value of the xchgRateDealId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXchgRateDealId() {
        return xchgRateDealId;
    }

    /**
     * Sets the value of the xchgRateDealId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXchgRateDealId(String value) {
        this.xchgRateDealId = value;
    }

}
