//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.01 at 10:11:10 AM IST 
//


package com.sample.pain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalOrganisationIdentification1CodeWire.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExternalOrganisationIdentification1CodeWire">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BANK"/>
 *     &lt;enumeration value="CUST"/>
 *     &lt;enumeration value="DUNS"/>
 *     &lt;enumeration value="EMPL"/>
 *     &lt;enumeration value="GS1G"/>
 *     &lt;enumeration value="TXID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExternalOrganisationIdentification1CodeWire")
@XmlEnum
public enum ExternalOrganisationIdentification1CodeWire {

    BANK("BANK"),
    CUST("CUST"),
    DUNS("DUNS"),
    EMPL("EMPL"),
    @XmlEnumValue("GS1G")
    GS_1_G("GS1G"),
    TXID("TXID");
    private final String value;

    ExternalOrganisationIdentification1CodeWire(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExternalOrganisationIdentification1CodeWire fromValue(String v) {
        for (ExternalOrganisationIdentification1CodeWire c: ExternalOrganisationIdentification1CodeWire.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
