//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 02:29:15 PM IST 
//


package com.sample.pain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalPersonIdentification1CodeWire.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExternalPersonIdentification1CodeWire">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ARNU"/>
 *     &lt;enumeration value="CCPT"/>
 *     &lt;enumeration value="CUST"/>
 *     &lt;enumeration value="DRLC"/>
 *     &lt;enumeration value="EMPL"/>
 *     &lt;enumeration value="NIDN"/>
 *     &lt;enumeration value="SOSE"/>
 *     &lt;enumeration value="TXID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExternalPersonIdentification1CodeWire")
@XmlEnum
public enum ExternalPersonIdentification1CodeWire {

    ARNU,
    CCPT,
    CUST,
    DRLC,
    EMPL,
    NIDN,
    SOSE,
    TXID;

    public String value() {
        return name();
    }

    public static ExternalPersonIdentification1CodeWire fromValue(String v) {
        return valueOf(v);
    }

}
