//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.01 at 10:11:10 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:pts2:wire:iso:20022:tech:xsd:pain.001.001.08:V06", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sample.pain;
